# Site
repository: jalabulajunx/jalabulajunx.github.io
# favicon: images/favicon.ico

# Personal info
name: Sundararajan Mohan
title: Product Owner/Manager
email: sundararajan.mohan@hotmail.com
phone: +16474734505
# website: https://github.com/jalabulajunx

# Social links
twitter_username: leomattel
github_username:  jalabulajunx
# dribbble_username: jekyll
facebook_username: sundararajan.mohan
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sundararajanmohan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Sundar and I am a tech-savvy Product Manager who has: road mapped, gathered and managed product requirements; developed products, applications and learnt from their success and failures; focused on problem space by leveraging technical instincts and capabilities with business acumen and domain knowledge.

  I am most skilled in: <mark>Build and Maintain Products</mark>, <mark>Requirements Management</mark>, <mark>Analysis and Problem solving</mark>, and <mark>Domain consulting on Legal, Content, and Payments</mark>. Most importantly, I build <mark>trust</mark> and establish a <mark>lasting relationships</mark> with clients - without which I would <mark>fail</mark> in many aspects.

# Projects Section
projects_title: f(Sundararajan Mohan)

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: The odd section
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Product Management, some of my other interests and hobbies are:
    - Tinker: Raspberry Pi 3 powered Music Server using Airsonic to stream my personal collection of 30k Hi-Res [FLAC/WAV]; A DIY NAS server using FreeNAS for my extensive Photos database
    - Public Relations and Social Media Chair (2016 - 2018) for Dayton Thamizh Sangam. Designed and developed the website. Managed promotions and advertising on social media; ideate events to keep the community engaged
    - Hobbies: Novice Cellist and [Photographer](http://radnus.smugmug.com/); silver league volleyball player; a fine cook of South Indian vegetarian dishes; authored a memoir of my college days
    - Teacher: I teach grade 5/6 Math and English for <mark>remote schools in India</mark> via [eVidyaloka](https://www.evidyaloka.org/)
    - Active participant in <mark>Product Camps</mark>
    - To-dos: Cluster Pi to power music server with lossless streaming
    - <mark>New</mark>: I sort of learnt markdown and jekyll while building this resume

footnotes_title: Backstories
footnotes_content: |
    <p style="font-size: 1.2em; text-align: justify;">
      <a name="fn1">1.</a> The legacy Corrections platform was a major contributor <mark>($3.5M)</mark> to the overall revenue of the program. While the program itself had been replatformed, the corrections was not yet moved to the new platform. The idea of any migration is to ensure a seemless movement from old to new for the customers. We had carefully planned the migration path to ensure this smooth transition by understanding the workflows and processes involved that had very intricate details such as redacting several areas. So, we built a platform where UIs and underlying interactions can be <mark>built on the go (customized instantly) and deployed at sites without a need for release</mark>.<br/><br/>
      <a name="fn2">2.</a> The platform is a giant with <mark>millions of daily transaction</mark>. In order to understand the workflow of users and customers, I had built metrics and reports using <mark>Elastic DSL queries on Kibana</mark> platform. Also, in order to <mark>troubleshoot issues</mark> reported by customers, <mark>AWS logs</mark> were queried to understand their problems.<br/><br/>
      <a name="fn3">3.</a> Similar to corrections solution, another application residing on older technology needed a migration. The caveat: (1) It had the <mark>highest ever NPS</mark>, (2) It was bringing in <mark>annual revenue of over $30M</mark>, and (3) <a href="http://www.productmanagementtoday.com/edition/monthly-framework-management-2019-05?open-article-id=10540682" target="_blank">Whole Product</a> or nothing - monolithic migration, as the basic tenants of the product make up the entire product. The migration strategy needed to be constructed carefully so that it does not impact the customers migrating, and also has the least impact on learning. After extensive UX research, crude <mark>design sprints</mark> and many interviews later, we are on the cusp of releasing a product that will be superior to the Classic - and albeit numerous customer reviews and feedback on the alpha/beta/RC, one has to always learn from history - that we <mark>do not pull another Windows Vista</mark> &#128521;.<br/><br/>
      <a name="fn4">4.</a> On more than one occasions, I had recommended and produced results that entirely eliminated the need to develop new solutions. With concepts around <mark>reusability</mark>, I make sure we do not expend unnecessarily.<br/><br/>
      <a name="fn5">5.</a> AtTask was cloud-based a Project Management suite which was customized internally to track processes, the client wanted the workflow to be moved out of AtTask to Siebel CRM, I was invloved in this migration. I evaluated the <mark>cost parameters</mark> of existing license of AtTask and the <mark>cost involved in migration</mark>, and it did not make sense to make the move from AtTask. Thus, I had advised, based on my findings, to not to migrate - and they considered.
    </p>

# Footer
footer_show_references: true

# Build settings
remote_theme: jalabulajunx/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
