# Site
repository: jalabulajunx/jalabulajunx.github.io
# favicon: images/favicon.ico

# Personal info
name: Sundararajan Mohan
title: Product Owner/Manager
email: sundararajan.mohan@hotmail.com
phone: +16474734505
# website: https://github.com/jalabulajunx

# Social links
twitter_username: leomattel
github_username:  jalabulajunx
# dribbble_username: jekyll
facebook_username: sundararajan.mohan
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sundararajanmohan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile2.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Sundar and I am a tech-savvy Product Manager who has: road mapped, gathered and managed product requirements; developed products, applications and learnt from their success and failures; focused on problem space by leveraging technical instincts and capabilities with business acumen and domain knowledge.

  I am most skilled in: <mark>Build and Maintain Products</mark>, <mark>Requirements Management</mark>, <mark>Analysis and Problem solving</mark>, and <mark>Domain Consulting</mark>.

# Projects Section
projects_title: f(Sundararajan Mohan)

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: The odd section
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Product Management, some of my other interests and hobbies are:
    - Tinker: Raspberry Pi 3 powered Music Server using Airsonic to stream my personal collection of 30k Hi-Res [FLAC/WAV]; A DIY NAS server using FreeNAS for my extensive Photos database
    - Public Relations and Social Media Chair (2016 - 2018) for Dayton Thamizh Sangam. Designed and developed the website. Managed promotions and advertising on social media; ideate events to keep the community engaged
    - Hobbies: Novice Cellist and [Photographer](http://radnus.smugmug.com/); silver league volleyball player; a fine cook of South Indian vegetarian dishes; authored a memoir of my college days
    - Teacher: I teach grade 5/6 Math and English for <mark>remote schools in India</mark> via [eVidyaloka](https://www.evidyaloka.org/)
    - Active participant in <mark>Product Camps</mark>
    - To-dos: Cluster Pi to power music server with lossless streaming
    - <mark>New</mark>: I sort of learnt markdown and jekyll while building this resume

footnotes_title: Commentary
footnotes_content: |
    <p style="font-size: 1.2em; text-align: justify;">
      <a name="fn1">1.</a> The Client had migrated their primary platform applicaiton from legacy to latest technologies. While that was completed, the corrections department was still on the legacy, as it needed customized solutions on the new platform for every department. The legacy corrections solution was bringing in size-able revenue <mark>(15% of the total annual revenue)</mark>. So, we built a platform where UIs and underlying interactions can be <mark>built on the go and deployed at sites without a need for release</mark>.<br/><br/>
      <a name="fn2">2.</a> Similar to corrections solution, another application residing on older technology needed a migration. The caveat: It had the <mark>highest ever NPS</mark> and also was bringing in <mark>annual revenue of over $30M</mark>. The migration strategy needed to be constructed carefully so that it does not impact the customers migrating, and also has the least impact on learning. After extensive UX research and many interviews later, we are on the cusp of releasing a product that will be superior to the Classic - and are hoping that we <mark>do not pull a Windows Vista</mark> &#128521;.<br/><br/>
      <a name="fn3">3.</a> The new platform is a giant with <mark>millions of daily transaction</mark>. In order to understand the workflow of users and customers, I had built reports using <mark>Elastic DSL queries on Kibana</mark> platform. Also, in order to <mark>troubleshoot issues</mark> reported by customers, <mark>AWS logs</mark> were queried to understand their problems.<br/><br/>
      <a name="fn4">4.</a> On more than one occasions, I had recommended and produced results that entirely eliminated the need to develop new solutions. With concepts around reusability, I make sure we do not expend unnecessarily.
    </p>

# Footer
footer_show_references: true

# Build settings
remote_theme: jalabulajunx/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
