# Site
repository: jalabulajunx/jalabulajunx.github.io
# favicon: images/favicon.ico

# Personal info
name: Sundararajan Mohan
title: Product Owner/Manager
email: sundararajan.mohan@hotmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: leomattel
github_username:  jalabulajunx
# dribbble_username: jekyll
facebook_username: sundararajan.mohan
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sundararajanmohan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hell, my name's Sundar and I'm a tech-savvy Product Manager who has: road mapped, gathered and managed product requirements; developed products, applications and learnt from their success and failures; focused on problem space by leveraging technical instincts and capabilities with business acumen and domain knowledge.

  I am most skilled in: <mark>Product Management</mark>, <mark><mark>Product Management</mark>, <mark>Requirements Management</mark>, <mark>Analysis and Problem solving</mark>, <mark>Domain Consulting</mark>, <mark>Application Demonstration</mark>, <mark>Workflow Analysis and Development</mark>, <mark>Process Improvement</mark>, <mark>Project Management</mark>, <mark>Change management</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
